global:
  # Gmail SMTP settings
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'alert@gmail.com'
  smtp_auth_username: 'alert@gmail.com'
  smtp_auth_password: 'your-app-password' # Use Gmail App Password if 2FA enabled

route:
  # Top-level routing
  group_by: ['alertname', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
#  receiver: 'gmail-critical'   # <--- default receiver
  receiver: 'googlechat-medium'   # <--- default receiver
  routes:
    # Critical alerts -> Gmail only
    - match:
        severity: critical
      receiver: 'gmail-critical'

    # Medium alerts -> Gmail + Google Chat
    - match:
        severity: medium
      receiver: 'gmail-medium'
      continue: true   # ensures it also matches next route
    - match:
        severity: medium
      receiver: 'googlechat-medium'

    # Low alerts -> Google Chat only
    - match:
        severity: low
      receiver: 'googlechat-low'

receivers:
  # Gmail receivers
  - name: 'gmail-critical'
    email_configs:
      - to: 'you@gmail.com'
        send_resolved: true

  - name: 'gmail-medium'
    email_configs:
      - to: 'you@gmail.com'
        send_resolved: true

  # Google Chat receivers (webhook)
  - name: 'googlechat-medium'
    webhook_configs:
      - url: 'https://chat.googleapis.com/v1/spaces/AAAAzQ_tW60/messages?key&token'
        send_resolved: true

  - name: 'googlechat-low'
    webhook_configs:
      - url: 'https://chat.googleapis.com/v1/spaces/AAAAzQ_tW60/messages?key&token'
        send_resolved: true

