{
 "title": "Qdrant Demo Dashboard",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Qdrant Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "app_info{job=\"qdrant-cluster-demo\"}",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Collections total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "collections_total{job=\"qdrant-cluster-demo\"}",
     "legendFormat": "collection_total"
    }
   ]
  },
  {
   "title": "cluster peers total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster_peers_total{job=\"qdrant-cluster-demo\"}",
     "legendFormat": "cluster_peers_total"
    }
   ]
  },
  {
   "title": "cluster term",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster_term{job=\"qdrant-cluster-demo\"}",
     "legendFormat": "cluster term"
    }
   ]
  },
  {
   "title": "cluster commit",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster_commit{job=\"qdrant-cluster-demo\"}",
     "legendFormat": "cluster_commit"
    }
   ]
  },
  {
   "title": "cluster_pending_operations_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "rate(cluster_pending_operations_total{job=\"qdrant-cluster-demo\"}[5m])",
     "legendFormat": "cluster_pending_operations_total"
    }
   ]
  },
  {
   "title": "Collections vector total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "collections_vector_total{job=\"qdrant-cluster-demo\"}",
     "legendFormat": "collections_vector_total"
    }
   ]
  },
  {
   "title": "rest_responses_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rest_responses_total{job=\"qdrant-cluster-demo\", exported_endpoint=\"/collections/{name}/points\", method=\"PUT\"}",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "rest_responses_total{job=\"qdrant-cluster-demo\", exported_endpoint=\"/collections/{name}/points/search\", method=\"POST\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}