{
 "title": "Qdrant Cloud Public Dashboard",
 "description": "Grafana dashboard for Qdrant clusters deployed on Qdrant Cloud Platform.",
 "tags": [ "qdrant" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster_id",
    "label": "Cluster ID",
    "query": {
     "query": "label_values(qdrant_operator_cluster_info_total,cluster_id)"
    }
   },
   {
    "name": "api_endpoint",
    "label": "API Endpoint",
    "query": {
     "query": "label_values({__name__=~\"grpc_responses_total|rest_responses_total\", qdrant_source=\"native\"}, endpoint)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_info{pod=~\"qdrant-$cluster_id-.*\"},pod)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(kube_pod_container_info{container!=\"kubectl\"},container)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{pod=~\"$pod\"},namespace)"
    }
   },
   {
    "name": "traefik_service",
    "query": {
     "query": "label_values(traefik_service_requests_total{service=~\".*-qdrant-$cluster_id-.*\"},service)"
    }
   },
   {
    "name": "pvc_storage",
    "query": {
     "query": "label_values(kube_persistentvolumeclaim_info{namespace=~\"$namespace\", persistentvolumeclaim=~\"qdrant-storage-qdrant-$cluster_id-.*\"},persistentvolumeclaim)"
    }
   },
   {
    "name": "pvc_snapshots",
    "query": {
     "query": "label_values(kube_persistentvolumeclaim_info{namespace=~\"$namespace\", persistentvolumeclaim=~\"qdrant-snapshots-qdrant-$cluster_id-.*\"},persistentvolumeclaim)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node Status Over Time",
     "type": "state-timeline",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(pod) (kube_pod_status_phase{phase=\"Running\", pod=~\"qdrant-$cluster_id-.*\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Node Restarts Over Time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (pod,container) (ceil(delta(kube_pod_container_status_restarts_total{pod=~\"$pod\",namespace=~\"$namespace\"}[$__range])))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Cluster Peers",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "max(cluster_peers_total)", "legendFormat": "Peers" }
     ]
    },
    {
     "title": "Cluster State",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "min(cluster_working_state{state=\"working\"})",
       "legendFormat": "State"
      }
     ]
    },
    {
     "title": "Active Replicas (Min)",
     "type": "state-timeline",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 13 },
     "targets": [
      {
       "expr": "min(collection_active_replicas_min)",
       "legendFormat": "Min Active Replicas"
      }
     ]
    },
    {
     "title": "Active Replicas (Max)",
     "type": "state-timeline",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 13 },
     "targets": [
      {
       "expr": "max(collection_active_replicas_max)",
       "legendFormat": "Max Active Replicas"
      }
     ]
    },
    {
     "title": "Cluster Update Lag",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(time() - cluster_last_update_timestamp_seconds)",
       "legendFormat": "Update Lag"
      }
     ]
    }
   ]
  },
  {
   "title": "Collections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Collections",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "max(collections_total)", "legendFormat": "Collections" }
     ]
    },
    {
     "title": "Approximate Vector Count",
     "type": "timeseries",
     "description": "Physical vector count across all nodes. Replicas are summed up, so the total may be higher than the logical vector count.",
     "gridPos": { "h": 6, "w": 20, "x": 4, "y": 1 },
     "targets": [
      {
       "expr": "sum by (collection, vector) (collection_vectors)",
       "legendFormat": "{{collection}} {{vector}}"
      }
     ]
    },
    {
     "title": "Running Optimizations",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "sum by (id) (collection_running_optimizations)",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Shard Transfers (Outgoing)",
     "type": "status-history",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
     "targets": [
      {
       "expr": "sum by (id) (collection_shard_transfer_outgoing)",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Update Queue Length",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
     "targets": [
      {
       "expr": "sum by (id) (collection_update_queue_length)",
       "legendFormat": "{{id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Endpoints",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (endpoint, status) (rate(grpc_responses_total{qdrant_source=\"native\", endpoint=~\"$api_endpoint\"}[$__rate_interval]))",
       "legendFormat": "gRPC {{endpoint}} [{{status}}]"
      },
      {
       "expr": "sum by (method, endpoint, status) (rate(rest_responses_total{qdrant_source=\"native\", endpoint=~\"$api_endpoint\"}[$__rate_interval]))",
       "legendFormat": "{{method}} {{endpoint}} [{{status}}]"
      }
     ]
    },
    {
     "title": "Latency Distribution",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "sum by (le) (rate({__name__=~\"grpc_responses_duration_seconds_bucket|rest_responses_duration_seconds_bucket\", qdrant_source=\"native\", endpoint=~\"$api_endpoint\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (pod,container) (rate(container_cpu_usage_seconds_total{pod=~\"$pod\",container=~\"$container\"}[$__rate_interval]))",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "min (kube_pod_container_resource_requests{namespace=~\"$namespace\", pod=~\"$pod\", container=\"$container\", unit=\"core\"})",
       "legendFormat": "Request"
      },
      {
       "expr": "min(kube_pod_container_resource_limits{namespace=~\"$namespace\", pod=~\"$pod\", container=\"$container\", unit=\"core\"})",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Memory usage: RSSAnon",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by (pod) (qdrant_node_rssanon_bytes{pod=~\"$pod\"})",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "min(kube_pod_container_resource_limits{pod=~\"$pod\",container=\"qdrant\",unit=\"byte\"})",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Memory usage: Page cache",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (pod,container) (container_memory_cache{pod=~\"$pod\",container=~\"$container\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "IOPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum by (pod,container,device) (irate(container_fs_writes_total{pod=~\"$pod\",namespace=~\"$namespace\",container=~\"$container\"}[2m])+rate(container_fs_reads_total{pod=~\"$pod\",namespace=~\"$namespace\",container=~\"$container\"}[2m]))",
       "legendFormat": "{{pod}}:{{device}}"
      }
     ]
    },
    {
     "title": "IO Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{id!=\"/\",pod=~\"qdrant-$cluster_id-.*\"}[2m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Data Disk: Absolute usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"$pvc_storage\",namespace=~\"$namespace\"}",
       "legendFormat": "{{persistentvolumeclaim}}"
      },
      {
       "expr": "min(kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\"$pvc_storage\",namespace=~\"$namespace\"})",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "File descriptors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "sum by (pod,container) (container_file_descriptors{pod=~\"$pod\",namespace=~\"$namespace\",container=~\"$container\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Disk: Read",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (pod,container,device) (rate(container_fs_reads_bytes_total{pod=~\"$pod\",namespace=~\"$namespace\",container=~\"$container\"}[2m]))",
       "legendFormat": "{{pod}}:{{device}}"
      }
     ]
    },
    {
     "title": "Disk: Write",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (pod,container,device) (rate(container_fs_writes_bytes_total{pod=~\"$pod\",namespace=~\"$namespace\",container=~\"$container\"}[2m]))",
       "legendFormat": "{{pod}}:{{device}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average request latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (method,code,service,) (rate(traefik_service_request_duration_seconds_sum{service=~\"$traefik_service\"}[$__rate_interval]) / rate(traefik_service_requests_total{service=~\"$traefik_service\"}[$__rate_interval]))",
       "legendFormat": "{{method}} {{code}}"
      }
     ]
    },
    {
     "title": "Request Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (method) (rate(traefik_service_requests_total{service=~\"$traefik_service\"}[$__rate_interval]))",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Response Codes (by Method)",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(traefik_service_requests_total{service=~\".*-qdrant-$cluster_id.*\"}[12h])) by (method, code)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Ingress",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(traefik_service_requests_bytes_total{service=~\"$traefik_service\"}[$__rate_interval]))",
       "legendFormat": "{{service}}"
      }
     ]
    },
    {
     "title": "Egress",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(traefik_service_responses_bytes_total{service=~\"$traefik_service\"}[$__rate_interval]))",
       "legendFormat": "{{service}}"
      }
     ]
    },
    {
     "title": "Network: Transmit",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (pod) (rate(container_network_transmit_bytes_total{pod=~\"$pod\",namespace=~\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network: Receive",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (pod) (rate(container_network_receive_bytes_total{pod=~\"$pod\",namespace=~\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network: Transmit packets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (pod) (rate(container_network_transmit_packets_total{pod=~\"$pod\",namespace=~\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "sum by (pod) (rate(container_network_transmit_packets_dropped_total{pod=~\"$pod\",namespace=~\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "dropped {{pod}}"
      }
     ]
    },
    {
     "title": "Network: Receive packets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (pod) (rate(container_network_receive_packets_total{pod=~\"$pod\",namespace=~\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "sum by (pod) (rate(container_network_receive_packets_dropped_total{pod=~\"$pod\",namespace=~\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "dropped {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Process metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process Threads",
     "type": "timeseries",
     "description": "Number of used system threads",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum by(pod, container) (process_threads{cluster_id=\"$cluster_id\"})",
       "legendFormat": "Threads {{pod}}"
      }
     ]
    },
    {
     "title": "Process Major Page Faults",
     "type": "timeseries",
     "description": "Rate of major page faults encountered by the process",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by(pod) (rate(process_major_page_faults_total{cluster_id=\"$cluster_id\"}[$__rate_interval]))",
       "legendFormat": "Major Faults {{pod}}"
      }
     ]
    },
    {
     "title": "Process Minor Page Faults",
     "type": "timeseries",
     "description": "Rate of minor page faults encountered by the process",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by(pod) (rate(process_minor_page_faults_total{cluster_id=\"$cluster_id\"}[$__rate_interval]))",
       "legendFormat": "Minor Faults {{pod}}"
      }
     ]
    },
    {
     "title": "Process Open mmaps",
     "type": "timeseries",
     "description": "Number of open memory maps",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sum by(pod) (process_open_mmaps{cluster_id=\"$cluster_id\"})",
       "legendFormat": "Memory Maps {{pod}}"
      }
     ]
    },
    {
     "title": "System Max mmaps",
     "type": "stat",
     "description": "System wide maximum number of open memory maps",
     "gridPos": { "h": 3, "w": 5, "x": 7, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(system_max_mmaps{cluster_id=\"$cluster_id\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Process Open fds",
     "type": "timeseries",
     "description": "Number of open file descriptors",
     "gridPos": { "h": 8, "w": 7, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "sum by(pod) (qdrant_process_open_fds{cluster_id=\"$cluster_id\"})",
       "legendFormat": "File Descriptors {{pod}}"
      }
     ]
    },
    {
     "title": "Process Max fds",
     "type": "stat",
     "description": "Maximum number of open file descriptors",
     "gridPos": { "h": 3, "w": 5, "x": 19, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(qdrant_process_max_fds{cluster_id=\"$cluster_id\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Usage mmaps",
     "type": "timeseries",
     "description": "Relation between process open memory maps and system wide maximum number of open memory maps",
     "gridPos": { "h": 5, "w": 5, "x": 7, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by(cluster_id) (process_open_mmaps{cluster_id=\"$cluster_id\"}) / (sum by(cluster_id) (system_max_mmaps{cluster_id=\"$cluster_id\"}))",
       "legendFormat": "Usage {{cluster_id}}"
      }
     ]
    },
    {
     "title": "Usage fds",
     "type": "timeseries",
     "description": "Relation between the number of open file descriptors and the maximum number of open file descriptors",
     "gridPos": { "h": 5, "w": 5, "x": 19, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by(cluster_id) (qdrant_process_open_fds{cluster_id=\"$cluster_id\"}) / (sum by(cluster_id) (qdrant_process_max_fds{cluster_id=\"$cluster_id\"}))",
       "legendFormat": "Usage {{cluster_id}}"
      }
     ]
    }
   ]
  }
 ]
}